services:
  db:
    container_name: go_local_postgres
    image: postgis/postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}" ]
      interval: 30s
      retries: 3
    networks:
      - go_local_network
  api:
    container_name: go_local_api
    restart: always
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: go_local_postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
      GMAIL_MAIL: ${GMAIL_MAIL}
    depends_on:
      - db
    networks:
      - go_local_network
  # pgadmin:
  #   container_name: go_local_pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   networks:
  #     - go_local_network

networks:
  go_local_network:
    driver: bridge
