definitions:
  backend_internal_models.ErrorResponse:
    properties:
      message:
        type: string
      type:
        type: integer
    type: object
  backend_internal_models.PreferenceSurveyAnswer:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      options:
        items:
          $ref: '#/definitions/backend_internal_models.PreferenceSurveyAnswerOption'
        type: array
      questionID:
        type: integer
      surveyID:
        type: integer
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  backend_internal_models.PreferenceSurveyAnswerOption:
    properties:
      answerID:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      optionID:
        type: integer
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/preference/change-preference-survey:
    post:
      consumes:
      - application/json
      description: Handle the submission of a preference survey
      produces:
      - application/json
      responses: {}
      summary: Handle Survey
      tags:
      - preference
  /api/preference/preference-survey:
    get:
      consumes:
      - application/json
      description: Get the preference survey
      produces:
      - application/json
      responses: {}
      summary: Get Survey
      tags:
      - preference
  /api/preference/preference-survey/answer:
    post:
      consumes:
      - application/json
      description: Handle the submission of survey answers
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/backend_internal_models.PreferenceSurveyAnswer'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/backend_internal_models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/backend_internal_models.ErrorResponse'
      summary: Handle Survey Answer
      tags:
      - preference
  /api/recommendation/recommendation:
    get:
      consumes:
      - application/json
      description: Get recommendations based on user preferences
      produces:
      - application/json
      responses: {}
      summary: Get Recommendations
      tags:
      - recommendation
swagger: "2.0"
